# Generated by Django 2.0.2 on 2019-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
